version: '3'

services:
  front:
    build: ./nuxt-front
    container_name: nuxt-front
    command: yarn docker
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    networks:
      - nuxt-sample-network
    platform: linux/amd64

  api:
    build: ./express-api
    container_name: express-api
    command: yarn start
    restart: unless-stopped
    environment:
      - PORT=3001
      # - HOST= 
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    networks:
      - nuxt-sample-network
    platform: linux/amd64

  api_db:
    image: mongo:latest
    container_name: express-api_db
    volumes:
      - mongodb_api:/data/db
    networks:
      - nuxt-sample-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-docker
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf"
    depends_on:
      - front
      - api
    networks:
      - nuxt-sample-network

volumes:
  mongodb_api:

networks:
  nuxt-sample-network:
    driver: bridge
