#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FORBIDDEN_HTTPS_URL="https://github.com/jhk-im/vue-samples.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:jhk-im/vue-samples.git" # insert your remote url (ssh)

protected_branch='refs/heads/master'  
current_branch=$(git symbolic-ref HEAD)
url=$(git config --get remote.origin.url)

if [ $protected_branch = $current_branch ]  
then  
  if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
  then
    exit 0 # Forked Project 에서는 제한하지 않음
  fi
    echo "DO NOT PUSH it test"
    exit 1 # 금지된 ref 로 push 를 실행하면 에러
else
    exit 0 # push will execute
fi  